#version 430 core
layout(local_size_x = 256) in;

layout(std430, binding = 16)  buffer GridParticleKeys  { uint keys[]; };
layout(std430, binding = 12) buffer RadixHistograms { uint histograms[]; };

uniform uint numberOfParticles;
uniform uint shift;

shared uint localHistogram[16];

void main() {
    uint localId  = gl_LocalInvocationID.x;
    uint globalId = gl_GlobalInvocationID.x;
    uint groupId  = gl_WorkGroupID.x;

    if (localId < 16) {
        localHistogram[localId] = 0;
    }

    memoryBarrierShared();
    barrier();

    if (globalId < numberOfParticles) {
        uint key = keys[globalId];
        uint digit = (key >> shift) & 0xFu;
        atomicAdd(localHistogram[digit], 1u);
    }
    memoryBarrierShared();
    barrier();

    if (localId < 16) {
        histograms[groupId * 16u + localId] = localHistogram[localId];
    }
}