#version 450 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer ParticlePositions { float positions[]; };
layout(std430, binding = 1) buffer ParticleVelocities { float velocities[]; };
layout(std430, binding = 2) buffer ParticlePredictedPositions { float predictedPositions[]; };

uniform float dt;
uniform uint numberOfParticles;
uniform float particleRadius;
uniform vec4 planes[6];

vec3 getPositionVec3(uint id) {
    uint base = id * 3;
    return vec3(positions[base], positions[base+1], positions[base+2]);
}

vec3 getPredictedPositionVec3(uint id) {
    uint base = id * 3;
    return vec3(predictedPositions[base], predictedPositions[base+1], predictedPositions[base+2]);
}

vec3 getVelocityVec3(uint id) {
    uint base = id * 3;
    return vec3(velocities[base], velocities[base+1], velocities[base+2]);
}


void setPredictedPosVec3(uint id, vec3 val) {
    uint base = id * 3;
    predictedPositions[base]   = val.x;
    predictedPositions[base+1] = val.y;
    predictedPositions[base+2] = val.z;
}

void setPosVec3(uint id, vec3 val) {
    uint base = id * 3;
    positions[base]   = val.x;
    positions[base+1] = val.y;
    positions[base+2] = val.z;
}

void setVelocityVec3(uint id, vec3 val) {
    uint base = id * 3;
    velocities[base] = val.x;
    velocities[base+1] = val.y;
    velocities[base+2] = val.z;
}

void resolveCollision(inout vec3 pos, inout vec3 vel, bool ignoreVelocity) {
    for (int i = 0; i < 6; i++) {
        vec3 normal = planes[i].xyz;
        float h = dot(pos, normal) + planes[i].w;
        if (h + particleRadius >= 0.0) {
            pos = pos - h * normal - normal * particleRadius;
            if (!ignoreVelocity) {
                float normalSpeed = dot(normal, vel);
                if (normalSpeed > 0.0)
                    vel -= normal * normalSpeed;
            }
        }
    }
}

uniform vec3 obstaclePos[16];
uniform float obstacleRadius[16];
uniform uint obstacleNum;
void resolveObstacleCollision(inout vec3 pos, inout vec3 vel, bool ignoreVelocity){
    for (uint i = 0; i < obstacleNum; i++){
        vec3 OP = pos - obstaclePos[i];
        float dist = length(OP);
        if (dist < obstacleRadius[i]){
            OP = normalize(OP);

            if (dist < 1e-6){
                pos = obstaclePos[i] + obstacleRadius[i] * vec3(0.0, 1.0, 0.0);
                
                if (!ignoreVelocity){
                    float normalSpeed = dot(vec3(0.0, 1.0, 0.0), vel);
                    if (normalSpeed > 0.0)
                    vel -= vec3(0.0, 1.0, 0.0) * normalSpeed;
                }

                continue;
            }

            pos = obstaclePos[i] + obstacleRadius[i] * OP;

            if (!ignoreVelocity){
                float normalSpeed = dot(OP , vel);
                if (normalSpeed > 0.0)
                vel -= OP * normalSpeed;
            }
        }
    }
}

void main(){
    uint id = gl_GlobalInvocationID.x;
    if (id >= numberOfParticles) return;

    vec3 predictedPos = getPredictedPositionVec3(id);
    vec3 pos = getPositionVec3(id);
    vec3 vel = (predictedPos - pos) / dt;
    pos = predictedPos;
    resolveObstacleCollision(pos, vel, false);
    resolveCollision(pos, vel, false);

    setPosVec3(id, pos);
    setVelocityVec3(id, vel);
}