#version 430 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 2) buffer ParticlePredictedPositions { float predictedPositions[]; };
layout(std430, binding = 3) buffer Densities { float densities[]; };
layout(std430, binding = 4) buffer NearDensities { float nearDensities[]; };
layout(std430, binding = 5) buffer Deltas { float deltas[]; };
layout(std430, binding = 8) buffer GridCellStart { uint cellStart[]; };
layout(std430, binding = 9) buffer GridCellEnd { uint cellEnd[]; };

uniform uint tableSize;
uniform float spacing;
uniform uint numberOfParticles;

uniform float smoothingRadius;

uniform float dt;
uniform float targetDensity;
uniform float pressureMultiplier;
uniform float nearPressureMultiplier;

vec3 getPredictedPositionVec3(uint id) {
    uint base = id * 3;
    return vec3(predictedPositions[base], predictedPositions[base+1], predictedPositions[base+2]);
}

int floatToIntCoord(float val) {
    return int(floor(val / spacing));
}

uint coordToHash(ivec3 coord) {
    int h = (coord.x * 92837111) ^ (coord.y * 689287499) ^ (coord.z * 283923481);
    return uint(h & 0x7FFFFFFF) % tableSize;
}


void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= numberOfParticles) return;

    vec3 pos = getPredictedPositionVec3(id);

    float pressure = pressureMultiplier * (densities[id] - targetDensity);
    float nearPressure = nearPressureMultiplier * nearDensities[id];

    int startX = floatToIntCoord(pos.x - smoothingRadius);
    int startY = floatToIntCoord(pos.y - smoothingRadius);
    int startZ = floatToIntCoord(pos.z - smoothingRadius);
    int endX   = floatToIntCoord(pos.x + smoothingRadius);
    int endY   = floatToIntCoord(pos.y + smoothingRadius);
    int endZ   = floatToIntCoord(pos.z + smoothingRadius);

    for (int x = startX; x <= endX; x++) {
        for (int y = startY; y <= endY; y++) {
            for (int z = startZ; z <= endZ; z++) {
                uint hash = coordToHash(ivec3(x, y, z));
                uint start = cellStart[hash];
                uint end   = cellEnd[hash];

                if (start == 0xFFFFFFFFu) continue;

                for (uint i = start; i < end; i++) {
                    if (i == id) continue;

                    vec3 rij = getPredictedPositionVec3(i) - getPredictedPositionVec3(id);
                    float r = length(rij);
                    if (r <= 1e-6 || r >= smoothingRadius) continue;

                    vec3 dir = normalize(rij);
                    float q = 1.0 - (r / smoothingRadius);
                    vec3 D = dt * dt * (pressure * q + nearPressure * q * q) * dir;

                    deltas[3 * id] -= 0.5f * D.x;
                    deltas[3 * id + 1] -= 0.5f * D.y;
                    deltas[3 * id + 2] -= 0.5f * D.z;

                    deltas[3 * i] += 0.5f * D.x;
                    deltas[3 * i + 1] += 0.5f * D.y;
                    deltas[3 * i + 2] += 0.5f * D.z;
                }
            }
        }
    }
}