#version 430 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer ParticlePositions { float positions[]; };
layout(std430, binding = 1) buffer ParticleVelocities { float velocities[]; };
layout(std430, binding = 2) buffer ParticlePredictedPositions { float predictedPositions[]; };
layout(std430, binding = 5) buffer GridCellStart { uint cellStart[]; };
layout(std430, binding = 6) buffer GridCellEntries { uint cellEntries[]; };

uniform uint tableSize;
uniform float spacing;
uniform uint numberOfParticles;

uniform float dt;
uniform float viscosityMultiplier;
uniform float smoothingRadius;
uniform float particleMass;
uniform vec3 gravity;
uniform vec4 planes[6];
uniform float particleRadius;

vec3 getPositionVec3(uint id) {
    uint base = id * 3;
    return vec3(positions[base], positions[base+1], positions[base+2]);
}

vec3 getVelocityVec3(uint id) {
    uint base = id * 3;
    return vec3(velocities[base], velocities[base+1], velocities[base+2]);
}