#version 430 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 1) buffer ParticleVelocities { float velocities[]; };
layout(std430, binding = 2) buffer ParticlePredictedPositions { float predictedPositions[]; };
layout(std430, binding = 5) buffer Deltas { float deltas[]; };

uniform uint numberOfParticles;
uniform float particleRadius;
uniform vec4 planes[6];

vec3 getPredictedPosVec3(uint id) {
    uint base = id * 3;
    return vec3(predictedPositions[base], predictedPositions[base+1], predictedPositions[base+2]);
}

vec3 getVelocityVec3(uint id) {
    uint base = id * 3;
    return vec3(velocities[base], velocities[base+1], velocities[base+2]);
}

void setPredictedPosVec3(uint id, vec3 val) {
    uint base = id * 3;
    predictedPositions[base]   = val.x;
    predictedPositions[base+1] = val.y;
    predictedPositions[base+2] = val.z;
}

void setVelocityVec3(uint id, vec3 val) {
    uint base = id * 3;
    velocities[base]   = val.x;
    velocities[base+1] = val.y;
    velocities[base+2] = val.z;
}

void resolveCollision(inout vec3 pos, inout vec3 vel, bool ignoreVelocity) {
    vec3 updatedPos = pos;
    vec3 updatedVel = vel;

    for (int i = 0; i < 6; i++) {
        vec4 plane = planes[i];
        vec3 normal = plane.xyz;
        
        float h = dot(updatedPos, normal) + plane.w;
        if (h + particleRadius >= 0.0) {
            vec3 closestPoint = updatedPos - h * normal;
            updatedPos = closestPoint - normal * particleRadius;

            if (!ignoreVelocity) {
                float normalSpeed = dot(normal, updatedVel);
                if (normalSpeed > 0.0) {
                    updatedVel -= normal * normalSpeed;
                }
            }   
        }
    }

    pos = updatedPos;

    if (!ignoreVelocity) {
        vel = updatedVel;
    }
}

void main(){
    uint id = gl_GlobalInvocationID.x;
    if (id >= numberOfParticles) return;

    vec3 delta = vec3(deltas[3 * id], deltas[3 * id + 1], deltas[3 * id + 2]);
    vec3 pos = getPredictedPosVec3(id);
    vec3 vel = getVelocityVec3(id);

    pos += delta;
    resolveCollision(pos, vel, true);

    setPredictedPosVec3(id, pos);
    setVelocityVec3(id, vel);

    deltas[3*id] = 0.0;
    deltas[3*id+1] = 0.0;
    deltas[3*id+2] = 0.0;
}