#version 450 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 2) buffer ParticlePredictedPositions { float predictedPositions[]; };
layout(std430, binding = 3) buffer Densities { float densities[]; };
layout(std430, binding = 4) buffer NearDensities { float nearDensities[]; };
layout(std430, binding = 5) coherent volatile buffer Deltas { uint deltas[]; }; 
layout(std430, binding = 8) buffer GridCellStart { uint  cellStart[]; };
layout(std430, binding = 9) buffer GridCellEnd { uint  cellEnd[]; };

uniform uint  tableSize;
uniform float spacing;
uniform uint  numberOfParticles;
uniform float smoothingRadius;
uniform float dt;
uniform float targetDensity;
uniform float pressureMultiplier;
uniform float nearPressureMultiplier;

void atomicAddFloat(uint index, float value) {
    if (isnan(value) || isinf(value)) return;

    uint expected;
    uint desired;
    do {
        expected = deltas[index];
        desired = floatBitsToUint(uintBitsToFloat(expected) + value);
    } while (atomicCompSwap(deltas[index], expected, desired) != expected);
}

vec3 getPredictedPositionVec3(uint id) {
    uint base = id * 3;
    return vec3(predictedPositions[base], predictedPositions[base+1], predictedPositions[base+2]);
}

int floatToIntCoord(float val) {
    return int(floor(val / spacing));
}

uint coordToHash(ivec3 coord) {
    int h = (coord.x * 92837111) ^ (coord.y * 689287499) ^ (coord.z * 283923481);
    return uint(h & 0x7FFFFFFF) % tableSize;
}

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= numberOfParticles) return;

    //deltas[3 * id] = 0.0;
    //deltas[3 * id + 1] = 0.0;
    //deltas[3 * id + 2] = 0.0;

    //memoryBarrier();

    vec3 pos = getPredictedPositionVec3(id);
    float pressure = pressureMultiplier * (densities[id] - targetDensity);
    float nearPressure = nearPressureMultiplier * nearDensities[id];

    int startX = floatToIntCoord(pos.x - smoothingRadius);
    int startY = floatToIntCoord(pos.y - smoothingRadius);
    int startZ = floatToIntCoord(pos.z - smoothingRadius);
    int endX = floatToIntCoord(pos.x + smoothingRadius);
    int endY = floatToIntCoord(pos.y + smoothingRadius);
    int endZ = floatToIntCoord(pos.z + smoothingRadius);

    vec3 delta = vec3(0.0);

    for (int x = startX; x <= endX; x++) {
        for (int y = startY; y <= endY; y++) {
            for (int z = startZ; z <= endZ; z++) {
                uint hash  = coordToHash(ivec3(x, y, z));
                uint start = cellStart[hash];
                uint end   = cellEnd[hash];

                if (start == 0xFFFFFFFFu) continue;
                if (end > numberOfParticles) continue;
                if (start > end) continue;   

                for (uint ni = start; ni < end; ni++) {
                    uint j = ni;
                    if (j == id) continue;

                    vec3 rij = getPredictedPositionVec3(j) - pos;
                    float r  = length(rij);
                    if (r <= 1e-6 || r >= smoothingRadius) continue;

                    vec3  dir = normalize(rij);
                    float q   = 1.0 - (r / smoothingRadius);

                    vec3 D = dt * dt * (pressure * q + nearPressure * q * q) * dir;

                    if (any(isnan(D)) || any(isinf(D))) continue; 

                    delta -= 0.5 * D;

                    atomicAddFloat(3 * j, 0.5 * D.x);
                    atomicAddFloat(3 * j + 1, 0.5 * D.y);
                    atomicAddFloat(3 * j + 2, 0.5 * D.z);


                    //deltas[3 * j] += 0.5 * D.x;
                    //deltas[3 * j + 1] += 0.5 * D.y;
                    //deltas[3 * j + 2] += 0.5 * D.z;
                }
            }
        }
    }

    atomicAddFloat(3 * id, delta.x);
    atomicAddFloat(3 * id + 1, delta.y);
    atomicAddFloat(3 * id + 2, delta.z);
}
