#version 430 core
layout(local_size_x = 256) in;

layout(std430, binding = 6) buffer GridParticleKeys { uint gridParticleKeys[]; };
layout(std430, binding = 8) buffer GridCellStart { uint cellStart[]; };
layout(std430, binding = 9) buffer GridCellEnd { uint cellEnd[]; };

uniform uint numberOfParticles;

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= numberOfParticles) return;

    uint currentCell = gridParticleKeys[id];
    
    if (id == 0) {
        cellStart[currentCell] = 0;
    } else {
        uint leftCell = gridParticleKeys[id - 1];
        if (currentCell != leftCell) {
            cellStart[currentCell] = id;
            cellEnd[leftCell] = id;
        }
    }

    if (id == numberOfParticles - 1) {
        cellEnd[currentCell] = numberOfParticles;
    }
}